version: '2'

services:

  postgres:
    image: postgres:9.4
    volumes:
    - ./dockerdata/psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'db_username'
      POSTGRES_PASSWORD: 'db_password'
      POSTGRES_DB: 'db_pics'
    ports:
    - '5432:5432'